import { StyleSheet } from "@react-pdf/renderer";

export const colors = {
  text: "#18181B",
  muted: "#71717A",
  line: "#E4E4E7",
  paper: "#F5F6F8",
  card: "#FFFFFF",
  heading: "#111827",
  accent: "#0E7490",
  bar: "#E4E4E7",
  barFill: "#14B8C4",
  brand: "#0F172A",
};

export const statusPalette: Record<
  string,
  { background: string; color: string; border: string }
> = {
  None: { background: "#F4F4F5", color: "#3F3F46", border: "#D4D4D8" },
  "On Hold": { background: "#FFF7ED", color: "#9A3412", border: "#FDBA74" },
  "In Progress": { background: "#F0F9FF", color: "#075985", border: "#7DD3FC" },
  Delivered: { background: "#ECFDF5", color: "#065F46", border: "#6EE7B7" },
  Delay: { background: "#FEF2F2", color: "#991B1B", border: "#FCA5A5" },
};

export const styles = StyleSheet.create({
  page: {
    backgroundColor: colors.paper,
    color: colors.text,
    fontFamily: "Helvetica",
    fontSize: 9,
    paddingTop: 28,
    paddingBottom: 48,
    paddingHorizontal: 28,
  },
  footer: {
    position: "absolute",
    left: 28,
    right: 28,
    bottom: 16,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: colors.line,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  footerText: {
    fontSize: 7,
    color: colors.muted,
  },
  brandBar: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    gap: 8,
  },
  brandMark: {
    width: 22,
    height: 22,
    objectFit: "contain",
  },
  brandName: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 2.4,
    color: colors.brand,
  },
  brandTag: {
    marginLeft: "auto",
    fontSize: 8,
    color: colors.muted,
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
    gap: 12,
  },
  headerLogo: {
    width: 56,
    height: 56,
    objectFit: "contain",
  },
  initials: {
    width: 56,
    height: 56,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.card,
    alignItems: "center",
    justifyContent: "center",
  },
  initialsText: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    color: colors.muted,
  },
  projectName: {
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    color: colors.heading,
    marginBottom: 4,
  },
  metaText: {
    fontSize: 9,
    color: colors.muted,
    marginBottom: 2,
  },
  badgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    marginBottom: 6,
  },
  badge: {
    borderWidth: 1,
    borderRadius: 3,
    paddingHorizontal: 5,
    paddingVertical: 2,
    marginRight: 4,
  },
  badgeText: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 0.5,
  },
  cardRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 8,
  },
  card: {
    flex: 1,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    padding: 10,
    minHeight: 160,
  },
  wideCard: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
  },
  cardTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: colors.heading,
    marginBottom: 8,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  coverCard: {
    flex: 1,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    padding: 10,
    minHeight: 160,
    alignItems: "center",
    justifyContent: "center",
  },
  coverLogo: {
    width: 72,
    height: 72,
    objectFit: "contain",
    marginBottom: 8,
  },
  coverName: {
    fontSize: 14,
    fontFamily: "Times-Bold",
    textAlign: "center",
    marginBottom: 4,
  },
  coverKicker: {
    fontSize: 8,
    letterSpacing: 1.4,
    color: colors.muted,
    textAlign: "center",
  },
  paragraph: {
    fontSize: 8,
    lineHeight: 1.45,
    marginBottom: 4,
    color: colors.text,
  },
  heading2: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    marginBottom: 4,
    marginTop: 2,
    color: colors.heading,
  },
  heading3: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    marginBottom: 3,
    color: colors.heading,
  },
  listItem: {
    flexDirection: "row",
    marginBottom: 2,
  },
  listMark: {
    width: 10,
    fontSize: 8,
    color: colors.text,
  },
  listBody: {
    flex: 1,
    fontSize: 8,
    lineHeight: 1.4,
  },
  image: {
    width: 150,
    height: 80,
    objectFit: "contain",
    marginVertical: 4,
  },
  empty: {
    fontSize: 8,
    color: colors.muted,
  },
  checkRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  checkMark: {
    width: 12,
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
  },
  checkText: {
    fontSize: 8,
    color: colors.text,
  },
  deliveredRow: {
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  deliveredName: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: colors.heading,
    marginBottom: 2,
  },
  deliveredLink: {
    fontSize: 8,
    color: colors.accent,
    textDecoration: "underline",
  },
  progressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  progressValue: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: colors.heading,
  },
  table: {
    borderWidth: 1,
    borderColor: colors.line,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#FAFAFA",
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    paddingVertical: 5,
    paddingHorizontal: 6,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    paddingVertical: 6,
    paddingHorizontal: 6,
    alignItems: "center",
  },
  colMilestone: { width: "46%" },
  colStatus: { width: "22%" },
  colDate: { width: "16%" },
  tableHeadText: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 0.4,
    color: colors.muted,
  },
  tableCell: {
    fontSize: 8,
    color: colors.text,
  },
});
